config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'dashboard/index'
  end

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :faqs
  end

  resources :sessions
  resources :faqs

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates_uniqueness_of :email
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_filter :authorize

  def index
  end
end

app/controllers/admin/faqs_controller.rb
class Admin::FaqsController < ApplicationController
  before_action :authorize

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
    @faq = Faq.find(params[:id])
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to admin_faqs_url, notice: 'Faq was faqfully created.' }
        format.json { render action: 'show', status: :created, location: @faq }
      else
        format.html { render action: 'new' }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    @faq = Faq.find(params[:id])
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to admin_faqs_url, notice: 'Faq was faqfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to admin_faqs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:faq, :answer)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @user = User.all
  end
  
	def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	respond_to do |format|
  		if @user.save
  			format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
  			format.json {render json: @user, status: :created, location: [:admin,@user] }
  		else
  			format.html { render action: "new" }
  			format.json { render json: @user.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes!(user_params)
      redirect_to admin_path, notice: "User has been updated."
    else
      render "edit"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  	def current_user
  		@current_user ||=	User.find(session[:user_id]) if session[:user_id]
  	end

  	helper_method :current_user

  	def authorize
  		redirect_to login_url, alert: "Not authorized" if current_user.nil?
  	end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController

	def index
		@faqs = Faq.all
	end

	def show
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to admin_url, notice: "Logged in!"
  	else
  		flash.now.alert = "Email or Password invalid"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to login_path, notice: "Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/faqs_helper.rb
module Admin::FaqsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Administration</h1>

<ul>
	<li><%= link_to 'Manage Users', admin_users_path %></li>
	<li><%= link_to 'Manage FAQs', admin_faqs_path %></li>
</ul>

app/views/admin/faqs/edit.html.erb
<h1>Edit FAQ</h1>

<%= form_for [:admin, @faq] do |f| %>
  <% if @faq.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @faq.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :faq %><br />
    <%= f.text_field :faq %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="actions"><%= f.submit "Update" %></div>
<% end %>

app/views/admin/faqs/index.html.erb
<h1>FAQs</h1> 

<% @faqs.each do |faq| %>
	<div>
		<h2><%= link_to faq.faq, edit_admin_faq_path(faq) %></h2>
		<%= simple_format faq.answer %>
	</div>
<% end %>

<%= link_to 'New FAQ', new_admin_faq_path %>

app/views/admin/faqs/new.html.erb
<h1>New FAQ</h1>

<%= form_for [:admin, @faq] do |f| %>
  <% if @faq.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @faq.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :faq %><br />
    <%= f.text_field :faq %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="actions"><%= f.submit "Save" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update User" %></div>
<% end %>

app/views/admin/users/index.html.erb
<h1>Users</h1> 

<% @user.each do |user| %>
	<div>
		<h2><%= link_to user.email, edit_admin_user_path(user) %></h2>
	</div>
<% end %>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/faqs/index.html.erb
<h1>FAQs</h1> 

<% @faqs.each do |faq| %>
	<div>
		<h2><%= faq.faq %></h2>
		<%= simple_format faq.answer %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playdough</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= link_to "Admin home", admin_url %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>